name: XXXX
on:
  watch:
    types: started
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: |
        curl https://rclone.org/install.sh | sudo bash
        wget -q https://github.com/1nthemachine/pt_encode/releases/download/gclone/gclone.gz
        gunzip gclone.gz
        sudo mv gclone /usr/bin/gclone
        chmod +x /usr/bin/gclone
        sudo apt install unrar -y -q
    - name: Inject Rclone config
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      run: |
        wget -q https://github.com/$GITHUB_REPOSITORY/raw/main/sa_encode1.rar
        unrar -p'${{ secrets.RAR_PSWD }}' e sa_encode1.rar ~/accounts/
        index=`ls -l ~/accounts |grep "^-"|wc -l`
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${RCLONE_CONF/1.json/$((RANDOM%$index+1)).json}
        EOF
    - name: CHDWEB
      run: |
        sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        rclone lsd pt_part1:/CHDBits_Panini/ | sort -k 2 | awk '$2 == "${{ secrets.DATE }}"' | awk '{print "+ "$5"/*-CHDWEB/**"}' > chdweb.output && echo "- **" >> chdweb.output
        cat chdweb.output
        gclone copy ${{ secrets.FILE5_PATH }}  --stats-log-level NOTICE -P --stats 30s --cache-chunk-total-size 25G --transfers=12 --drive-chunk-size 128M --max-backlog 1000 --drive-skip-depth 1 --checksum --filter-from chdweb.output
